name: arch-gym
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - beautifulsoup4=4.11.1=pyha770c72_0
  - brotlipy=0.7.0=py39hb9d737c_1004
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.10.11=h06a4308_0
  - certifi=2022.9.24=py39h06a4308_0
  - cffi=1.15.1=py39he91dace_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - cloudpickle=2.2.0=pyhd8ed1ab_0
  - colorama=0.4.5=pyhd8ed1ab_0
  - cryptography=38.0.1=py39hd97740a_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - gym=0.21.0=py39hef51801_2
  - icu=70.1=h27087fc_0
  - idna=3.4=pyhd8ed1ab_0
  - joblib=1.2.0=pyhd8ed1ab_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libblas=3.9.0=16_linux64_openblas
  - libcblas=3.9.0=16_linux64_openblas
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libgomp=12.1.0=h8d9b700_16
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=16_linux64_openblas
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libsqlite=3.39.4=h753d276_0
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.44.2=h166bdaf_0
  - libxml2=2.10.2=h4c7fe37_1
  - libxslt=1.1.35=h8affb1d_0
  - libzlib=1.2.12=h166bdaf_4
  - lxml=4.9.1=py39hb9d737c_0
  - ncurses=6.3=h27087fc_1
  - nodejs=18.10.0=h96d913c_0
  - openssl=1.1.1q=h7f8727e_0
  - pandas=1.5.0=py39h4661b88_0
  - pip=22.2.2=pyhd8ed1ab_0
  - psutil=5.9.2=py39hb9d737c_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.13=h9a8a25e_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2022.4=pyhd8ed1ab_0
  - pygraphviz=1.10
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.1=pyhd8ed1ab_1
  - scikit-learn=1.1.2=py39he5e8d7e_0
  - scipy=1.9.1=py39h8ba3f38_0
  - setuptools=65.4.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.39.4=h4ff8645_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.12=h27826a3_0
  - tqdm=4.64.1=pyhd8ed1ab_0
  - tzdata=2022d=h191b570_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.12=h166bdaf_4
  - pip:
    - absl-py==1.2.0
    - sympy==1.11.1
    - plotly==5.11.0

    
